# Generated by Django 6.0 on 2026-02-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('cart_id', models.AutoField(db_column='cart_id', primary_key=True, serialize=False)),
                ('qty', models.IntegerField(db_column='product_qty', default=1)),
            ],
            options={
                'db_table': 'user_cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('order_id', models.AutoField(db_column='order_id', primary_key=True, serialize=False)),
                ('customer_name', models.CharField(db_column='customer_name', max_length=255)),
                ('customer_email', models.EmailField(blank=True, db_column='customer_email', max_length=254, null=True)),
                ('customer_phone', models.CharField(blank=True, db_column='customer_phone', max_length=20, null=True)),
                ('customer_address', models.CharField(db_column='customer_address', max_length=255)),
                ('total', models.DecimalField(db_column='total', decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'user_orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('product_id', models.AutoField(db_column='product_id', primary_key=True, serialize=False)),
                ('product_price', models.DecimalField(db_column='product_price', decimal_places=2, max_digits=10)),
                ('product_image', models.BinaryField(db_column='product_image')),
                ('product_name', models.CharField(db_column='product_name', max_length=255)),
            ],
            options={
                'db_table': 'user_products',
                'managed': False,
            },
        ),
    ]
