# Generated by Django 6.0 on 2025-12-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('cart_id', models.AutoField(db_column='cart_id', primary_key=True, serialize=False)),
                ('product_id', models.IntegerField(db_column='product_id')),
                ('product_price', models.IntegerField(db_column='product_price')),
                ('qty', models.IntegerField(db_column='product_qty', default=1)),
            ],
            options={
                'db_table': 'user_cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('product_id', models.AutoField(db_column='product_id', primary_key=True, serialize=False)),
                ('product_price', models.CharField(db_column='product_price', max_length=255)),
                ('product_image', models.BinaryField(db_column='product_image', null=True)),
                ('product_name', models.CharField(db_column='product_name', max_length=255, null=True)),
            ],
            options={
                'db_table': 'user_products',
                'managed': False,
            },
        ),
    ]
