# Generated by Django 6.0 on 2026-02-25 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('cart_id', models.AutoField(db_column='cart_id', primary_key=True, serialize=False)),
                ('qty', models.IntegerField(db_column='product_qty', default=1)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_cart',
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('order_id', models.AutoField(db_column='order_id', primary_key=True, serialize=False)),
                ('customer_name', models.CharField(db_column='customer_name', max_length=255)),
                ('customer_email', models.EmailField(blank=True, db_column='customer_email', max_length=254, null=True)),
                ('customer_phone', models.CharField(blank=True, db_column='customer_phone', max_length=20, null=True)),
                ('customer_address', models.CharField(db_column='customer_address', max_length=255)),
                ('total', models.DecimalField(db_column='total', decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('customer_cart', models.ForeignKey(db_column='order_cart', on_delete=django.db.models.deletion.CASCADE, to='backend.usercart')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_orders',
            },
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('product_id', models.AutoField(db_column='product_id', primary_key=True, serialize=False)),
                ('product_price', models.DecimalField(db_column='product_price', decimal_places=2, max_digits=10)),
                ('product_image', models.BinaryField(db_column='product_image')),
                ('product_name', models.CharField(db_column='product_name', max_length=255)),
                ('product_user', models.ForeignKey(db_column='product_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_products',
            },
        ),
        migrations.AddField(
            model_name='usercart',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='backend.userproduct'),
        ),
    ]
