# Generated by Django 6.0 on 2025-12-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('order_id', models.AutoField(db_column='order_id', primary_key=True, serialize=False)),
                ('customer_name', models.CharField(db_column='customer_name', max_length=255)),
                ('customer_email', models.EmailField(blank=True, db_column='customer_email', max_length=254, null=True)),
                ('customer_phone', models.CharField(blank=True, db_column='customer_phone', null=True)),
                ('customer_address', models.CharField(db_column='customer_address', max_length=255)),
                ('total', models.DecimalField(db_column='order_cart', decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'user_orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(db_column='item_qty', default=1)),
                ('price', models.DecimalField(db_column='item_price', decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(db_column='line_total', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'user_order_items',
                'managed': False,
            },
        ),
    ]
