# Generated by Django 6.0 on 2026-02-24 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercart',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userorder',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userproduct',
            options={'managed': True},
        ),
    ]
