# Generated by Django 6.0 on 2025-12-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_userorder_userorderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOrderItem',
        ),
    ]
