# Generated by Django 6.0 on 2026-02-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_userproduct_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='product_image',
            field=models.ImageField(db_column='product_image', upload_to='products/'),
        ),
    ]
