# Generated by Django 6.0 on 2026-02-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_userproduct_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='product_image_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='product_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
